/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SingleRouteImport } from './routes/single'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as BatchRouteImport } from './routes/batch'
import { Route as IndexRouteImport } from './routes/index'

const SingleRoute = SingleRouteImport.update({
  id: '/single',
  path: '/single',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchRoute = BatchRouteImport.update({
  id: '/batch',
  path: '/batch',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/batch': typeof BatchRoute
  '/jobs': typeof JobsRoute
  '/settings': typeof SettingsRoute
  '/single': typeof SingleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/batch': typeof BatchRoute
  '/jobs': typeof JobsRoute
  '/settings': typeof SettingsRoute
  '/single': typeof SingleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/batch': typeof BatchRoute
  '/jobs': typeof JobsRoute
  '/settings': typeof SettingsRoute
  '/single': typeof SingleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/batch' | '/jobs' | '/settings' | '/single'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/batch' | '/jobs' | '/settings' | '/single'
  id: '__root__' | '/' | '/batch' | '/jobs' | '/settings' | '/single'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BatchRoute: typeof BatchRoute
  JobsRoute: typeof JobsRoute
  SettingsRoute: typeof SettingsRoute
  SingleRoute: typeof SingleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/single': {
      id: '/single'
      path: '/single'
      fullPath: '/single'
      preLoaderRoute: typeof SingleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch': {
      id: '/batch'
      path: '/batch'
      fullPath: '/batch'
      preLoaderRoute: typeof BatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BatchRoute: BatchRoute,
  JobsRoute: JobsRoute,
  SettingsRoute: SettingsRoute,
  SingleRoute: SingleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
