/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSingleRouteImport } from './routes/app.single'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppJobsRouteImport } from './routes/app.jobs'
import { Route as AppBatchRouteImport } from './routes/app.batch'

const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSingleRoute = AppSingleRouteImport.update({
  id: '/app/single',
  path: '/app/single',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/app/settings',
  path: '/app/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/app/jobs',
  path: '/app/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBatchRoute = AppBatchRouteImport.update({
  id: '/app/batch',
  path: '/app/batch',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/app/batch': typeof AppBatchRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/single': typeof AppSingleRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/app/batch': typeof AppBatchRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/single': typeof AppSingleRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app/batch': typeof AppBatchRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/single': typeof AppSingleRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app/batch'
    | '/app/jobs'
    | '/app/settings'
    | '/app/single'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to: '/app/batch' | '/app/jobs' | '/app/settings' | '/app/single' | '/app'
  id:
    | '__root__'
    | '/app/batch'
    | '/app/jobs'
    | '/app/settings'
    | '/app/single'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppBatchRoute: typeof AppBatchRoute
  AppJobsRoute: typeof AppJobsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSingleRoute: typeof AppSingleRoute
  AppIndexRoute: typeof AppIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/single': {
      id: '/app/single'
      path: '/app/single'
      fullPath: '/app/single'
      preLoaderRoute: typeof AppSingleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/jobs': {
      id: '/app/jobs'
      path: '/app/jobs'
      fullPath: '/app/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/batch': {
      id: '/app/batch'
      path: '/app/batch'
      fullPath: '/app/batch'
      preLoaderRoute: typeof AppBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AppBatchRoute: AppBatchRoute,
  AppJobsRoute: AppJobsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSingleRoute: AppSingleRoute,
  AppIndexRoute: AppIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
